# Generated by Django 2.0.13 on 2020-11-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBestPaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_string', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addresses', models.ManyToManyField(blank=True, to='blog.Address')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Route')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
