# Generated by Django 2.0.13 on 2020-11-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201126_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteBestPaths',
            new_name='RouteBestPath',
        ),
    ]
