# Generated by Django 3.1.1 on 2020-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
