# Generated by Django 2.0.13 on 2020-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201126_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routebestpath',
            old_name='path_string',
            new_name='best_path_string',
        ),
        migrations.AddField(
            model_name='routebestpath',
            name='best_path_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
