# Generated by Django 3.1.1 on 2020-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201009_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='number_of_locations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
