# Generated by Django 2.0.13 on 2020-11-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routebestpath',
            name='best_path_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routebestpath',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_paths', to='blog.Route'),
        ),
    ]
