# Generated by Django 3.1.1 on 2020-10-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_route_number_of_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_locations',
            field=models.IntegerField(verbose_name=range(2, 50)),
        ),
    ]
