# Generated by Django 2.0.13 on 2020-11-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201126_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBestPathLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Address')),
                ('route_best_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_path_locations', to='blog.RouteBestPath')),
            ],
        ),
    ]
