# Generated by Django 3.1.1 on 2020-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201017_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='route',
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_locations',
            field=models.IntegerField(),
        ),
    ]
