# Generated by Django 3.1.1 on 2020-10-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201017_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='content',
        ),
    ]
