# Generated by Django 2.0.13 on 2020-11-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_routebestpathlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='routebestpathlocation',
            options={'ordering': ('position',)},
        ),
    ]
