# Generated by Django 3.1.1 on 2020-10-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201017_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='author',
            new_name='user',
        ),
    ]
