# Generated by Django 3.1.1 on 2020-10-17 05:52

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201017_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_locations',
            field=blog.models.IntegerRangeField(),
        ),
    ]
