# Generated by Django 3.1.1 on 2020-10-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201018_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
