# Generated by Django 3.1.1 on 2020-10-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201018_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='route',
            new_name='routename',
        ),
    ]
