# Generated by Django 3.1.1 on 2020-10-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201018_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='routename',
            new_name='route_name',
        ),
    ]
