# Generated by Django 3.1.1 on 2020-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_address_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_distance', models.IntegerField()),
                ('return_distance', models.IntegerField()),
            ],
        ),
    ]
