# Generated by Django 3.1.1 on 2020-11-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
