# Generated by Django 3.1.1 on 2020-11-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('location_A', models.CharField(max_length=30)),
                ('location_B', models.CharField(max_length=30)),
                ('departure_distance', models.IntegerField()),
                ('return_distance', models.IntegerField()),
            ],
        ),
    ]
