# Generated by Django 3.1.1 on 2020-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='number',
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
