# Generated by Django 3.1.1 on 2020-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20201114_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='departure_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='return_distance',
            field=models.FloatField(),
        ),
    ]
