# Generated by Django 3.1.1 on 2020-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201114_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_A',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_B',
            field=models.CharField(max_length=50),
        ),
    ]
