# Generated by Django 3.1.1 on 2020-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20201114_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('ad', 'Abu Dhabi'), ('dxb', 'Dubai'), ('shj', 'Sharjah'), ('aj', 'Ajman'), ('rak', 'Ras Al Khaimah'), ('umq', 'Umm al Quwain'), ('fuj', 'Fujairah')], default='ad', max_length=6),
        ),
    ]
