# Generated by Django 3.1.1 on 2020-11-17 17:09

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0040_auto_20201116_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_locations',
            field=blog.models.IntegerRangeField(default=None),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('location', models.CharField(choices=[('aau', 'Al Ain University'), ('dalma', 'Dalma Mall'), ('mazyad', 'Mazyad Mall'), ('deer', 'Deerfield Mall'), ('yas', 'Yas Mall'), ('marina', 'Marina Mall'), ('khaldiya', 'Khalidiya Mall'), ('abudhabi', 'Abu Dhabi Mall'), ('wahda', 'Al Wahda Mall'), ('miraj', 'Miraj Restaurant'), ('havana', 'Havana Cafe'), ('pacifiko', 'Pacifiko Tiki Lounge'), ('ferrari', 'Ferrari World'), ('hosn', 'Qasr al hosn'), ('emirates', 'Emirates Palace'), ('louvre', 'Louvre Museum'), ('chricket', 'Sheikh Zayed Cricket Stadium'), ('yww', 'Yas Water World'), ('masdar', 'Masdar City'), ('ferrari', 'Ferrari World'), ('zaya', 'Zaya Nuraie Island')], default='NULL', max_length=30)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.country')),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.route')),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
