# Generated by Django 2.0.1 on 2020-11-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20201118_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
    ]
