# Generated by Django 3.1.3 on 2020-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20201119_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=None, max_length=30),
        ),
    ]
