# Generated by Django 3.1.3 on 2020-11-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20201121_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='make_initial_location',
        ),
    ]
