# Generated by Django 3.1.3 on 2020-11-20 21:58

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_remove_address_make_initial_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_locations',
            field=blog.models.IntegerRangeField(blank=True, default=None, null=True),
        ),
    ]
